name: high_chart
description: A chart library based on High Charts (.JS), able to build advanced   charts like Pie chart, linear chart, etc.
version: 2.0.4
homepage: https://github.com/senthilnasa/high_chart

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.7
  plugin_platform_interface: ^2.0.2
  url_launcher: ^6.2.1
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  plugin:
    platforms:
      android:
        package: me.senthilnasa.high_chart
        pluginClass: HighChartPlugin
      ios:
        pluginClass: HighChartPlugin
      web:
        pluginClass: HighChartWeb
        fileName: high_chart_web.dart